[tools]
bun = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
uv = "latest"
shfmt = "latest"
stylua = "latest"
awscli = { version = "latest", symlink_bins = true }
