#!/usr/bin/env bash

# Get the root directory of this repo
DIR="$( cd "$( dirname "$0" )" && pwd )"

mkdir -p ~/.config/nvim

# Fix shell colors
if [ ! -d ~/.config/base16-shell ]
then
  git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
fi

# Install neovim, python3
brew tap neovim/neovim
brew install hub zsh neovim python3 yarn tidy-html5 rbenv ruby-install
pip3 install neovim

# Symlink all dotfiles to ~/
ln -sf $DIR/agignore ~/.agignore
ln -sf $DIR/gitconfig ~/.gitconfig
ln -sf $DIR/gitignore ~/.gitignore
ln -sf $DIR/hushlogin ~/.hushlogin
ln -sf $DIR/tern-config ~/.tern-config
ln -sf $DIR/vimrc ~/.config/nvim/init.vim
ln -sf ~/.config/nvim/init.vim ~/.vimrc
ln -sf $DIR/zshrc ~/.zshrc

# Symlink bin files
ln -sf $DIR/bin/db /usr/local/bin/db
ln -sf $DIR/bin/git-cleanup /usr/local/bin/git-cleanup
ln -sf $DIR/bin/git-sync /usr/local/bin/git-sync

# Install plug-vim
if [ ! -d ~/.local/share/nvim/plugged ]
then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Set up colors
base16_seti
