# ~/.zprofile

# sourced on login shells (after .zshenv but before .zshrc) put commands here
# that should run once at login good for setting up the initial environment

# initialize homebrew environment
eval "$(/opt/homebrew/bin/brew shellenv)"

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

# Android development
export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/platform-tools"

# Windsurf
export PATH="$HOME/.codeium/windsurf/bin:$PATH"
