# ~/.zshenv

# this file is always sourced, even for non-interactive shells put environment
# variables here that should be available to all zsh instances avoid anything
# that produces output or assumes an interactive shell

# ensure path uniqueness
typeset -U PATH path

# editors
export VISUAL="vim"
export EDITOR="vim"

# enable gpg daemon
export GPG_TTY=$(tty)

# pnpm
export PNPM_HOME="${HOME}/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="${PNPM_HOME}:$PATH" ;;
esac

# asdf version manager
export ASDF_DATA_DIR="${HOME}/.asdf"
path+=("${ASDF_DATA_DIR}/shims")

# postgres
path+=("/opt/homebrew/opt/postgresql@17/bin")

# zim framework home
export ZIM_HOME="${HOME}/.zim"
