# .zshenv

# ensure PATH uniqueness
typeset -U PATH path

# editors
export VISUAL="vim"
export EDITOR="vim"

# enable gpg daemon
export GPG_TTY=$(tty)

# pnpm
export PNPM_HOME="${HOME}/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="${PNPM_HOME}:$PATH" ;;
esac

# asdf
export ASDF_DATA_DIR="${HOME}/.asdf"
path+=("${ASDF_DATA_DIR}/shims")
