# ~/.zshrc

# starship prompt
eval "$(/opt/homebrew/bin/starship init zsh)"

# zsh plugins
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh

# environment
typeset -U PATH path

export VISUAL="vim"
export EDITOR="vim"
export GPG_TTY=$(tty)

# pnpm
export PNPM_HOME="${HOME}/Library/pnpm"
[[ ":$PATH:" != *":$PNPM_HOME:"* ]] && export PATH="$PNPM_HOME:$PATH"

# asdf
export ASDF_DATA_DIR="${HOME}/.asdf"
[[ -d "$ASDF_DATA_DIR/shims" ]] && path+=("$ASDF_DATA_DIR/shims")

# postgres
[[ -d "/opt/homebrew/opt/postgresql@17/bin" ]] && path+=("/opt/homebrew/opt/postgresql@17/bin")

# homebrew
[[ -f "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# zsh options
setopt NO_EXTENDED_GLOB
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
setopt HIST_REDUCE_BLANKS
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_MINUS
setopt PUSHD_SILENT
setopt AUTO_MENU
setopt AUTO_PARAM_SLASH
setopt COMPLETE_IN_WORD
setopt MENU_COMPLETE
setopt AUTO_CONTINUE
setopt CHECK_JOBS
setopt LONG_LIST_JOBS

# history
HISTFILE=${HOME}/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# aliases
alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdw='git diff --word-diff'
alias gl='git l'
alias gla='git la'
alias gpush='git push'
alias gs='git status -sb'
alias gshow='git show'

alias code="cursor"
alias c="code"
alias cat="bat --style=plain --paging=never"
alias less="bat --style=plain"
alias f='fzf'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
alias mkdir='mkdir -p'
alias df='df -h'
alias du='du -h'

# key bindings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^ ' autosuggest-accept
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^K' kill-line
bindkey '^U' backward-kill-line

# fzf
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'

# orbstack
[[ -f ~/.orbstack/shell/init.zsh ]] && source ~/.orbstack/shell/init.zsh

# android
if [[ -d "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home" ]]; then
  export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
fi

if [[ -d "$HOME/Library/Android/sdk" ]]; then
  export ANDROID_HOME="$HOME/Library/Android/sdk"
  path+=("$ANDROID_HOME/emulator" "$ANDROID_HOME/platform-tools")
fi

# local overrides
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# bun completions
[ -s "/Users/matt/.bun/_bun" ] && source "/Users/matt/.bun/_bun"
